"""empty message

Revision ID: 83be302d8cf8
Revises: cade78ab3b11
Create Date: 2023-10-26 00:19:17.309862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83be302d8cf8'
down_revision = 'cade78ab3b11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
